CREATE DATABASE IF NOT EXISTS nnptud_c4
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE nnptud_c4;

CREATE TABLE IF NOT EXISTS roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  description VARCHAR(500) NOT NULL DEFAULT '',
  isDeleted TINYINT(1) NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  fullName VARCHAR(255) NOT NULL DEFAULT '',
  avatarUrl VARCHAR(500) NOT NULL DEFAULT 'https://i.sstatic.net/l60Hf.png',
  status TINYINT(1) NOT NULL DEFAULT 0,
  roleId INT NULL,
  loginCount INT NOT NULL DEFAULT 0,
  isDeleted TINYINT(1) NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_roles FOREIGN KEY (roleId) REFERENCES roles(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
  CONSTRAINT chk_users_loginCount_nonnegative CHECK (loginCount >= 0)
);